### ISSUE TITLE
בניית מסך בריאקט 

### ISSUE THREAD

**Issue by EitanBarkochva** [Final-Project-supermarket/main#7]
אהלן יהונדב אשמח שתתחיל ללמוד ריאקט ולכן תיקח עליך את המשימה של בניית מסך רישום.

יהיה פקד טקסט ל שם פרטי שם משפחה אימל וססמה ותמלא אובייקט מתאים לזה.

**Comment by nadavsuissa** [comment]
כן חושב שטוב ליהונדב להתחיל ללמוד ריאקט, מנגד אני חושב שאני כבר אדאג לדף רישום כמו שאתה מתאר בקבוצה אז אולי שווה להתמקד במשהו אחר?

**Comment by nadavsuissa** [comment]
CREATED AND DONE - REGISTER
