### ISSUE TITLE
יצירת רשימת קניות 

### ISSUE THREAD

**Issue by EitanBarkochva** [Final-Project-supermarket/main#8]
עדיין לא סגרנו איך יוצרים את רשימת הקניות .
אפשרות רגילה זה תמונות ולחיצה עליהם זה הבחירה שלהם ומתחת רושמים כמות.
אפשרות שנייה זה למלא קובץ אקסל עם שם הפריט במדויק וכן את הכמות ובתוכנה נוסיף את הברקוד ונמצא את המוצר.
כמובן שניקח לא יותר מ 50 מוצרים.
או שניהם שזה הכי עדיף.
כמובן שנשמור את רשימת הקניות לכל לקוח.
עמית כפרה תתחיל עם ריאקט בבניית מסך שמציג תמונה שמתחתיו ניתן לתת כמות ולחיצה עליו מכניס לאובייקט מוצר ולבסוף יש מערך של 
מוצרים.

**Comment by nadavsuissa** [comment]
אני חושב להוסיף לכל אובייקט יוזר מערך של רשימת קניות, ככה יהיה לנו תיעוד, ויכולת לבצע מעקב חכם, כמובן שהכל בגדר מחשבה

**Comment by nadavsuissa** [comment]
ניתן ליצור רשימת קניות - לסגור
